import { and, desc, eq, like, or, sql, type SQL } from 'drizzle-orm';
import { AdminHeader, AdminPageIntro } from '@/components/admin/admin-shell';
import { StockAdjustment } from '@/components/admin/stock-adjustment';
import { getDb } from '@/db';
import { products, productVariants, stockMovements, users } from '@/db/schema';
import { requireAdmin } from '@/lib/admin-auth';

export default async function AdminStockPage({ searchParams }: { searchParams: Promise<{ q?: string; muc?: string }> }) {
  const admin = await requireAdmin(); const query = await searchParams; const conditions: SQL[] = [];
  if (query.q?.trim()) { const pattern = `%${query.q.trim().replaceAll('%','')}%`; conditions.push(or(like(productVariants.sku, pattern), like(products.name, pattern), like(productVariants.color, pattern))!); }
  if (query.muc === 'low') conditions.push(and(eq(productVariants.active, true), sql`${productVariants.stock}-${productVariants.reservedStock}<=3`)!);
  const db = getDb();
  const rows = await db.select({ id: productVariants.id, sku: productVariants.sku, color: productVariants.color, size: productVariants.size, stock: productVariants.stock, reservedStock: productVariants.reservedStock, active: productVariants.active, updatedAt: productVariants.updatedAt, productName: products.name }).from(productVariants).innerJoin(products, eq(productVariants.productId, products.id)).where(conditions.length ? and(...conditions) : undefined).orderBy(desc(productVariants.updatedAt)).limit(300);
  const history = await db.select({ id: stockMovements.id, sku: productVariants.sku, productName: products.name, quantityDelta: stockMovements.quantityDelta, stockBefore: stockMovements.stockBefore, stockAfter: stockMovements.stockAfter, reason: stockMovements.reason, type: stockMovements.type, createdAt: stockMovements.createdAt, actor: users.email }).from(stockMovements).innerJoin(productVariants, eq(stockMovements.variantId, productVariants.id)).innerJoin(products, eq(productVariants.productId, products.id)).leftJoin(users, eq(stockMovements.actorUserId, users.id)).orderBy(desc(stockMovements.createdAt)).limit(50);
  return <main className="min-h-screen bg-[#f1f1eb]"><AdminHeader email={admin.email} /><section className="mx-auto max-w-[1300px] px-4 py-10 sm:px-8 lg:py-14"><AdminPageIntro title="Kho hàng" description="Kiểm tra tồn khả dụng và lưu lịch sử mỗi lần nhập, xuất hoặc điều chỉnh kho." />
    <form className="mt-6 flex flex-col gap-3 rounded-2xl bg-white p-4 sm:flex-row"><input name="q" defaultValue={query.q} placeholder="Tìm tên sản phẩm, SKU hoặc màu" className="min-h-11 flex-1 rounded-lg border border-black/20 px-3 text-base" /><select name="muc" defaultValue={query.muc || ''} className="min-h-11 rounded-lg border border-black/20 bg-white px-3 text-base"><option value="">Tất cả SKU</option><option value="low">Sắp hết (≤ 3)</option></select><button className="min-h-11 rounded-full bg-[#dfff00] px-6 text-sm font-black">Lọc kho</button></form>
    <div className="mt-6 space-y-3">{rows.map((row) => <article key={row.id} className="rounded-2xl border border-black/10 bg-white p-5"><div className="grid gap-4 sm:grid-cols-[1fr_100px_100px_100px_auto] sm:items-center"><div><p className="font-black">{row.productName}</p><p className="mt-1 font-mono text-xs text-neutral-500">{row.sku} · {row.color} / {row.size}</p></div><div><p className="text-xs text-neutral-500">Tồn</p><p className="text-xl font-black">{row.stock}</p></div><div><p className="text-xs text-neutral-500">Đang giữ</p><p className="text-xl font-black">{row.reservedStock}</p></div><div><p className="text-xs text-neutral-500">Khả dụng</p><p className={`text-xl font-black ${row.stock-row.reservedStock<=3 ? 'text-red-600':''}`}>{row.stock-row.reservedStock}</p></div><StockAdjustment variantId={row.id} current={row.stock} reserved={row.reservedStock} updatedAt={row.updatedAt} /></div></article>)}</div>
    <section className="mt-10 rounded-2xl border border-black/10 bg-white p-5 sm:p-7"><h2 className="text-2xl font-black">Lịch sử kho gần đây</h2><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b border-black">{['Thời gian','Sản phẩm / SKU','Thay đổi','Trước → Sau','Lý do','Người thực hiện'].map((h)=><th key={h} className="px-3 py-3 text-xs uppercase">{h}</th>)}</tr></thead><tbody className="divide-y divide-black/10">{history.map((entry)=><tr key={entry.id}><td className="px-3 py-4 text-xs">{new Date(entry.createdAt).toLocaleString('vi-VN')}</td><td className="px-3 py-4"><p className="font-bold">{entry.productName}</p><p className="font-mono text-xs">{entry.sku}</p></td><td className={`px-3 py-4 font-black ${entry.quantityDelta>0?'text-green-700':'text-red-600'}`}>{entry.quantityDelta>0?'+':''}{entry.quantityDelta}</td><td className="px-3 py-4">{entry.stockBefore} → {entry.stockAfter}</td><td className="px-3 py-4">{entry.reason}</td><td className="px-3 py-4 text-xs">{entry.actor || 'Hệ thống'}</td></tr>)}</tbody></table>{history.length===0&&<p className="py-10 text-center text-sm text-neutral-500">Chưa có lịch sử điều chỉnh kho.</p>}</div></section>
  </section></main>;
}
